### PR TITLE
Added: VGA VMode

### PR DESCRIPTION
**Pull request by doctorxyz**
Some days ago when iohanntachy asked for an uLE VGA VMode (http://psx-scene.com/forums/f113/any-chances-ulaunchelf-vga-mode-156142/) I remembered that I have already done this 7 years ago - and I almost lost it.

### CODE REVIEW

**Comment by AKuHAK** [comment]
Ok its fine but is there an option to force safe mode? I mean if you for example totally removed vga mode from your console you will see black screen with no option to get picture. I understand that some programs like opl doesn't need such feature but uLaunchELF can be called like low-level app ))) so it need such a feature.

**Comment by doctorxyz** [comment]
I see. How about we implement the [L1+R1+L2+R2] button combo pressing on uLE boot to activate the safe mode ?

**Comment by doctorxyz** [comment]
Okay, I have just caught some bugs so I will fix them first - And include the above combo as well; therefore, please reject this pull request.

**Comment by AKuHAK** [comment]
yeah this will be great! Maybe you can add this combo for reverting all settings to their defaults? :) Thanks in advance

**Comment by uyjulian** [comment]
actually, you can just fix your problem, then rebase on this branch whenever you get to it.

**Comment by doctorxyz** [comment]
AKuHAK, agreed - ATM I am commiting changes into my personal repo. Once finished, I will test this myself (on VGA monitor and TV) to check if everything is okay. 
uyjulian, thanks for the tips; after finishing the tests I will try to do what you suggested above.

**Pull request merged**
