### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by rickgaiser** [comment]
Did you intend to include all those commits in this PR, or only the last one?

The .gitlab-ci.yml does not belong here for sure, and the newlib changes make it compile and run in PCSX2, but there's still issues with a real ps2, right?

**Comment by AKuHAK** [comment]
So is it safe to merge? All changes are bugless?

**Comment by AKuHAK** [comment]
And. I thought that we are using ps2dev:ps2dev docker inage

**Comment by uyjulian** [comment]
Don't merge yet

**Comment by uyjulian** [comment]
I tested it on my PS2, and it works fine

**Comment by Jay-Jay-OPL** [comment]
Just wanted to let you know that I've tested compiling uLE up to commit: 2452243 and though it runs okay when you launch it from a PS2 console, it fails to open the following item on the default menu: About uLE -- it simply crashes uLE when attempting to.

And when you run it again and browse to the path: `MISC/` -- it will not open the directory.

I also compiled the ELF using an updated installation (currently as of today) of ps2dev to install ps2toolchain, ps2sdk, and etc.

I hope that helps...

**Comment by uyjulian** [comment]
Works for me…  
Try this https://github.com/uyjulian/uLaunchELF/suites/837746017/artifacts/9419692

**Comment by Jay-Jay-OPL** [comment]
@uyjulian -- I just tested the one you linked to download.  Still acts the same way.

Here are my steps:
1) I place this ELF file inside a folder I have on my USB Flash HDD: `mass:/test/BOOT.ELF`
2) ran the ELF file and when I attempt the things I reported above, it still fails for me.

P.S. I suspected perhaps the LAUNCHELF.CFG file next to it was the culprit, so I deleted it, and I tested it again, but noticed that it seems when I press a button, it's too sensitive -- it sort of flashes a screen and then reverts back to the screen I was first looking at.  So I can't even see mass, it goes so fast that I can see it for a second, but then it reverts back same thing with MISC -- at the very least I can browse mc0 and mc1.

Plus when I attempt to select About uLE  -- that seems to still crash the application, because it then becomes inoperable.

Plus even after trying to go into the SETTING to see if something I can change to fix the issue, it tends to freeze up on me.

Hopefully others can test this.  I am using a SLIM SCPH-77001 V15 with an authentic DualShock 2 controller.

**Comment by uyjulian** [comment]
Fast input should be fixed.

https://github.com/uyjulian/uLaunchELF/suites/838792791/artifacts/9442240

**Comment by Jay-Jay-OPL** [comment]
Bingo!  That fixed the issue I reported above.

Now I spot a new issue (sorry).

Under the uLE **Startup Settings**, if I select to change the **Pad Mapping** to: `X : OK  and O : CANCEL` and then save my uLE settings.  When I restart uLE, I see that it didn't change that setting.

Plus, when I check the `LAUNCHELF.CFG` file, I see it didn't change the line.  Even though uLE indicated that it did save my settings.  So I assume that it's not changing that line in the CFG file when attempting to change that setting.

I'll keep checking if more things are broken.  -- That is why I like testing it from my flash drive than replacing my main BOOT file on my memory card. ;)

**Comment by uyjulian** [comment]
Fixed pad mapping.  
https://github.com/uyjulian/uLaunchELF/suites/839146452/artifacts/9448830

**Comment by uyjulian** [comment]
Should be ready for merge

**Comment by AKuHAK** [comment]
ok, wLe into a new era.

**Comment by Jay-Jay-OPL** [comment]
Okay, I tested your above version and you were able to fix most of the issues, but there is still one more bug -- I sort of mentioned in my third update above, but here a better explanation.

uLE will read correctly the `LAUNCHELF.CNF` file if found here: `mc0:/SYS-CONF/`  and if you have altered some of your changes to it, it will save your changes and next time you open uLE it will respect your changes.  So that works okay.

But, if you keep that CNF file next to the ELF file -- let's say in this directory: `mass:/test/`:
```
mass:/test/BOOT.ELF
mass:/test/LAUNCHELF.CNF
```
uLE will save your changes to that path, but it will NOT read it from there, it will simply ignore it.

I believe that is a bug, since older uLE versions would give that CNF file first priority and would read it if it was found near the ELF file.

**Pull request merged**
