### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by AKuHAK** [comment]
About irx removing - we need to know what does @dp193 think about it. These binaries are precompiled specially, so I dont think that we have to rearrange this in such a way.

**Comment by sp193** [comment]
IMO we aren't going to adjust the source code for the old libraries, so it is just a waste of time to recompile them often. They are "old" because they don't belong to the PS2SDK and have not been updated in a long time.

Sent from my Sony Xperia™ smartphone

**Comment by AKuHAK** [comment]
You can add into makefile special rule for recompiling "old" libraries and disable it by default. And maybe without removing this from our branch. Other commits are fine as I see.

**Comment by uyjulian** [comment]
The makefile will only compile the old libraries once, then it will only compile changed files.
Same with any other source file.

Compiling using `make -j8` takes 7.399 seconds on my dual-core computer.

**Pull request merged**
